import { auth } from "../../auth"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
 return (
   <html lang="en">

    
      <body >
      {session?.user ? <div>
          <img src={session?.user.avatar_img_url} alt="User Avatar" />
          <p className="text-red-500">{session?.user.username}</p>
    </div>:  null}
      
        {children}</body>
    </html>
  );
}
